[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
brach = "current"
features = [
    "builder",
    "cache",
    "framework",
    "model",
    "standerd_framework",
    "rustls_backend",
    "utils"
]